### PR TITLE
Adopt `pkg:flutter_lints` 1.0

### PR DESCRIPTION
**Pull request by domesticmouse**
Note, this change appears to have broken the back button in the titlebar. I'm guessing there was an incorrect non-null field somewhere that I cleaned up.

Tests would really help =)

### CODE REVIEW

**Comment by esDotDev** [comment]
Wow, thanks for all the work! Might take us a bit to land this, but we'll make sure it gets in.

**Comment by esDotDev** [comment]
It seems the back button issue is due to the TitleBar not rebuilding when `selectedBook` is changed, not really sure why it worked before... 

To fix, change line 36 of `app_title_bar.dart` to:
`bool canGoBack = context.select((BooksModel m) => m.currentBook != null);`

**Comment by esDotDev** [comment]
Curious, is `prefer_relative_imports` now recommended by the flutter team? I know that mixing relative and package can lead to confusion, so we had standardized on package imports.

From my experience, Android Studio can often get fail to provide code-hinting when trying to import things using relative import, and refactoring is also more likely to break when you drag a file into a different folder, which is why we ended up settling on package level.

**Comment by domesticmouse** [comment]
Thanks!

**Pull request merged**
